### PR TITLE
Set install name in `LIBFLAGS`

### PR DESCRIPTION
**Pull request by carlocab**
My previous PR (#16) deliberately set the install name at install time
instead of at build time, since this is the correct time to determine
the library's install name.

However, if you prefer to do this during build time instead, then there
is no need to call `install_name_tool`. We can pass the appropriate
flags to the linker instead.

### CODE REVIEW

**Comment by maandree** [comment]
These looks much better. But is there any particular reason why determining the install name shall be at install time? To me it looks like `install_name_tool` only rewrites the binary, which should only be done at build time, and all paths that files are install to, as well as version numbers, should be set at built time as the code may need to know these when it's are being compiled (for example, a program may need to know if it's resource files are installed to /usr/share or /usr/local/share, and which subdirectory (the name of the subdirectory should be the package name, not the software's name)).

**Comment by carlocab** [comment]
If I do `make` (i.e. without `install`) then anything I link against `libkeccak` (e.g. for testing) will look for it in `$PREFIX/lib` since it has an install name of `$PREFIX/lib/likeccak.$LIBEXT`.

When I don't set the install name, then it will simply have an install name of `libkeccak.$LIBEXT`, which means the dynamic loader will at least try to check my current working directory for `libkeccak` when I run anything I've linked against it.

Indeed, setting the install name before install time makes `libkeccak` unusable from the source root without resorting to workarounds. Delaying the determination of the install name until install time makes a non-installed `libkeccak` at least somewhat useable without having to resort to install-name rewriting with `install_name_tool`.

**Comment by maandree** [comment]
Then it sounds the correct thing to do is run `install_name_tool` on the library, but after it has been installed (it is perfectly okay to do during `install` since: modify files in the destination directory is okay, but not modifying files in the source directory). This would also leave the library file in the project directory unmodified so that the linker doesn't by mistake to the installed versions when testing.

**Comment by carlocab** [comment]
Yes, good point. I've pushed a new commit that does this instead.

**Comment by maandree** [comment]
I noticed that the patch doesn't seem to be correct. `install_name_tool` is called on `$(DESTDIR)$(PREFIX)/lib/libkeccak.$(LIBEXT)`, rather than`$(DESTDIR)$(PREFIX)/lib/libkeccak.$(LIBMINOREXT)`, and before `$(DESTDIR)$(PREFIX)/lib/libkeccak.$(LIBEXT)` is created.

I also assume that `install_name_tool` will accept a `--` before the last argument (before $(DESTDIR)…). Correct?

**Comment by carlocab** [comment]
> I noticed that the patch doesn't seem to be correct. `install_name_tool` is called on `$(DESTDIR)$(PREFIX)/lib/libkeccak.$(LIBEXT)`, rather than`$(DESTDIR)$(PREFIX)/lib/libkeccak.$(LIBMINOREXT)`, and before `$(DESTDIR)$(PREFIX)/lib/libkeccak.$(LIBEXT)` is created.

Yes, my mistake. It should probably be called on `$(DESTDIR)$(PREFIX)/lib/libkeccak.$(LIBMINOREXT)`. Or it can be moved to the last step of the `install` target so that it is called after `$(DESTDIR)$(PREFIX)/lib/libkeccak.$(LIBEXT)` is created.

> I also assume that `install_name_tool` will accept a `--` before the last argument (before $(DESTDIR)…). Correct?

This is not the case, unfortunately.

**Comment by maandree** [comment]
I've corrected it now. Would you mind verifying that it works as expected before I make another release?

**Comment by carlocab** [comment]
Yes, just tested `make install` and it works as expected.

**Comment by maandree** [comment]
Great, thank you!

**Comment by maandree** [comment]
I've corrected it now. Would you mind verifying that it works as expected before I make another release?

**Pull request merged**
